### ISSUE TITLE
Uzem portrait renderer patch

### ISSUE THREAD

**Issue by danboid** [spacebararcade/SmokeyAndTheBandit#2]
I think you said on the Uzebox forum that you had patched Uzem so that it was able to render its video in portrait / 'tate mode?

Do you still have this patched code? If so, could you please submit a PR to Uzem in the Uzebox repo or just upload an archive of your patched code please?

Lee (D3thAdd3r) plans to add this to cuzebox but when he'll get round to it is anyones guess.

Thanks

**Comment by diggerbonk** [comment]
Oh man, that was going on 9 years ago. I'll dig around and see what I can find :-)

**Comment by danboid** [comment]
No worries, turns out someone else had already done a similar thing and released their code on the forum, it just never got merged into Uzem but now DA has done just that:

https://uzebox.org/forums/viewtopic.php?t=1753

Thanks!
